import Navbar from "@/components/navbar/Navbar";
import "./globals.scss";
import Navbar2 from "@/components/profile/Navbar2";
import Sidebar from "@/components/sidebar/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Navbar2 />
        <Sidebar />
        {/* 
        <Dashboard>{children}</Dashboard>
        <Footer /> */}
      </body>
    </html>
  );
}
